ConsultaPersistenciaDadosDengue/Models/DadosDengueModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ConsultaPersistenciaDadosDengue.Models
{
    public class DadosDengueModel
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long id { get; set; }
        public int se { get; set; }
        public double casos_est { get; set; }
        public int casos { get; set; }
        public int nivel { get; set; }
    }
}

ConsultaPersistenciaDadosDengue/Models/ErrorViewModel.cs
namespace ConsultaPersistenciaDadosDengue.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ConsultaPersistenciaDadosDengue/Controllers/Implements/IDadosDengueController.cs
using Microsoft.AspNetCore.Mvc;

namespace ConsultaPersistenciaDadosDengue.Controllers.Implements
{
    public interface IDadosDengueController
    {
        Task<IActionResult> Index();
        Task<IActionResult> AtualizaDadosDengue();
    }
}

ConsultaPersistenciaDadosDengue/Controllers/Implements/IHomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace ConsultaPersistenciaDadosDengue.Controllers.Implements
{
    public interface IHomeController
    {
        IActionResult Index();
        IActionResult Error();
    }
}

ConsultaPersistenciaDadosDengue/Controllers/Interfaces/DadosDengueController.cs
using ConsultaPersistenciaDadosDengue.Controllers.Implements;
using ConsultaPersistenciaDadosDengue.Models;
using ConsultaPersistenciaDadosDengue.Services.Interface;
using Microsoft.AspNetCore.Mvc;

namespace ConsultaPersistenciaDadosDengue.Controllers.Interfaces
{
    public class DadosDengueController : Controller, IDadosDengueController
    {
        private readonly IDadosDengueService _dadosDengueService;

        public DadosDengueController(IDadosDengueService dadosDengueService)
        {
            _dadosDengueService = dadosDengueService;
        }

        public async Task<IActionResult> Index()
        {
            List<DadosDengueModel> data = await _dadosDengueService.ObtemDadosDengue();

            return View(data);
        }

        [HttpPost]
        public async Task<IActionResult> AtualizaDadosDengue()
        {
            await _dadosDengueService.AtualizaDadosDengue();
            return RedirectToAction("Index");
        }
    }
}

ConsultaPersistenciaDadosDengue/Controllers/Interfaces/HomeController.cs
using System.Diagnostics;
using ConsultaPersistenciaDadosDengue.Controllers.Implements;
using ConsultaPersistenciaDadosDengue.Models;
using Microsoft.AspNetCore.Mvc;

namespace ConsultaPersistenciaDadosDengue.Controllers.Interfaces
{
    public class HomeController : Controller, IHomeController
    {
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ConsultaPersistenciaDadosDengue/Views/DadosDengue/Index.cshtml
@model List<DadosDengueModel>

@{
    ViewData["Title"] = "Consulta Dados Dengue";
}

<h2 class="title">Dados de Dengue dos Últimos 6 Meses</h2>

<form method="post" asp-action="AtualizaDadosDengue">
    <button type="submit" class="btn btn-primary">Atualizar Dados da Dengue</button>
</form>

@if (Model != null && Model.Count > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th>Semana Epidemiológica</th>
                <th>Casos Estimados</th>
                <th>Casos Notificados</th>
                <th>Nível de Alerta</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@FormatarSemanaEpidemiologica(@item.se)</td>
                    <td>@item.casos_est</td>
                    <td>@item.casos</td>
                    <td>@item.nivel</td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Nenhum dado disponível.</p>
}

<style>
    .title{
        margin-bottom: 30px;
    }
    .btn{
        margin-bottom:10px;
    }
</style>

@functions {
    private string FormatarSemanaEpidemiologica(int se)
    {
        string seStr = se.ToString();
        string ano = seStr.Substring(0, 4);
        string semana = seStr.Substring(4, 2);
        return $"{ano}-{semana}";
    }
}

ConsultaPersistenciaDadosDengue/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="text-center">
    <h1 class="display-4">Bem vindo</h1>
    <p>A consulta de dados da dengue. Consulte os dados dos ultimos 6 meses da doença.</p>
</div>

ConsultaPersistenciaDadosDengue/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ConsultaPersistenciaDadosDengue</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ConsultaPersistenciaDadosDengue.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Consultor de Dados da Dengue</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DadosDengue" asp-action="Index">Dados da Dengue</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - ConsultaPersistenciaDadosDengue
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>